### Numpy Useage

In [1]:
import numpy as np

In [2]:
# make ndarray 
arr = np.array([1,2,3,4,5,6])
print(arr,end=': np.array([1,2,3,4,5,6]) \n\n')
arr = np.arange(6)
print(arr,end=': np.arange(6) \n\n')
arr = np.arange(1,12,2)**2
print(arr,end=': np.arange(1,12,2)**2 \n\n')

# reshape 
arr = arr.reshape(2,3)
print(arr,end=':arr.reshape(2,3) \n\n')
arr = np.arange(12).reshape(2,6)
print(arr,end=': np.arange(12).reshape(2,6) \n\n')

[1 2 3 4 5 6]: np.array([1,2,3,4,5,6]) 

[0 1 2 3 4 5]: np.arange(6) 

[  1   9  25  49  81 121]: np.arange(1,12,2)**2 

[[  1   9  25]
 [ 49  81 121]]:arr.reshape(2,3) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]: np.arange(12).reshape(2,6) 



In [3]:
# calculate numpy
np.max(arr)

11

In [4]:
np.min(arr)

0

In [5]:
np.mean(arr)

5.5

In [6]:
np.std(arr)

3.452052529534663

In [7]:
np.add(arr,arr)

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [8]:
np.subtract(arr,arr) # 원소별 빼기

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [9]:
np.multiply(arr,arr) # 원소별 곱하기

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

In [10]:
print(arr, end='\n * 행렬곱 \n')
arr2 = np.arange(12)
arr2 = arr2.reshape(6,2)
print(arr2)

np.dot(arr,arr2) # 행렬곱 (dot-product)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
 * 행렬곱 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


array([[110, 125],
       [290, 341]])

In [11]:
arr1 = np.arange(1728).reshape(24,24,3)
arr2 = np.arange(1728).reshape(24,24,3)
arr3 = np.arange(1728).reshape(24,24,3)

files = []

files.append(arr1)
files.append(arr2)
files.append(arr3)

# c = np.stack([arr1, arr2, arr2], axis=0)
d = np.stack([f for f in files], axis=0)

# print(c.shape)
print(d.shape)

(3, 24, 24, 3)
