### Numpy Useage

In [1]:
import numpy as np

In [2]:
# make ndarray 
arr = np.array([1,2,3,4,5,6])
print(arr,end=': np.array([1,2,3,4,5,6]) \n\n')
arr = np.arange(6)
print(arr,end=': np.arange(6) \n\n')
arr = np.arange(1,12,2)**2
print(arr,end=': np.arange(1,12,2)**2 \n\n')

# reshape 
arr = arr.reshape(2,3)
print(arr,end=':arr.reshape(2,3) \n\n')
arr = np.arange(12).reshape(2,6)
print(arr,end=': np.arange(12).reshape(2,6) \n\n')

[1 2 3 4 5 6]: np.array([1,2,3,4,5,6]) 

[0 1 2 3 4 5]: np.arange(6) 

[  1   9  25  49  81 121]: np.arange(1,12,2)**2 

[[  1   9  25]
 [ 49  81 121]]:arr.reshape(2,3) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]: np.arange(12).reshape(2,6) 



In [3]:
arr_o = np.ones(10)
arr_o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
arr_z = np.zeros(10)
arr_z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# calculate numpy
np.max(arr)

11

In [6]:
np.min(arr)

0

In [7]:
np.mean(arr)

5.5

In [8]:
np.std(arr)

3.452052529534663

In [9]:
np.add(arr,arr)

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [10]:
np.subtract(arr,arr) # 원소별 빼기

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
np.multiply(arr,arr) # 원소별 곱하기

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

In [12]:
# argmax / argmin 최대값, 최소값의 위치 출력
t = np.arange(1,10)
print(np.argmax(t))
print(np.argmin(t))

8
0


In [13]:
print(arr, end='\n * 행렬곱 \n')
arr2 = np.arange(12)
arr2 = arr2.reshape(6,2)
print(arr2)

np.dot(arr,arr2) # 행렬곱 (dot-product)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
 * 행렬곱 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


array([[110, 125],
       [290, 341]])

In [14]:
arr1 = np.arange(1728).reshape(24,24,3)
arr2 = np.arange(1728).reshape(24,24,3)
arr3 = np.arange(1728).reshape(24,24,3)

files = []

files.append(arr1)
files.append(arr2)
files.append(arr3)

# c = np.stack([arr1, arr2, arr2], axis=0)
d = np.stack([f for f in files], axis=0)

# print(c.shape)
print(d.shape)

(3, 24, 24, 3)


### ndarray 조건 비교

In [15]:
x_arr = np.ones(15).reshape(3,5)
x_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
y_arr = np.array([])
y_arr = np.append(np.zeros(5),y_arr)
y_arr = np.append(np.ones(5),y_arr)
y_arr = np.append(np.zeros(5),y_arr)
y_arr = y_arr.reshape(3,5)
y_arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [17]:
x_arr[y_arr==1]=100
x_arr

array([[  1.,   1.,   1.,   1.,   1.],
       [100., 100., 100., 100., 100.],
       [  1.,   1.,   1.,   1.,   1.]])

### np.putmask

In [18]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
np.putmask(arr, arr>2, 100)
arr

array([  0,   1,   2, 100, 100, 100])

### np.transpose

In [36]:
data = np.arange(0,10)
data = data.reshape((1,2,5))
print(data.shape)
print(data)

(1, 2, 5)
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [37]:
data = data.transpose((0,1,2)) # 0차원, 1차원, 2차원 순이면 원본
print(data.shape)
print(data)

(1, 2, 5)
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [38]:
data = data.transpose((1,0,2)) # 0차원과 1차원을 바꾼다
print(data.shape)
print(data)

(2, 1, 5)
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


In [39]:
data = data.transpose((0,2,1)) # 3차원과 2차원을 바꾼다
print(data.shape)
print(data)

(2, 5, 1)
[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


### 난수발생

In [41]:
np.random.seed(42)
randn = np.random.randn(5) # 5개의 숫자 생성
randint = np.random.randint(0, 10, 5) # 0이상 10미만의 5개의 정수 생성

print(randn)
print(randint)

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
[7 4 3 7 7]
